### ISSUE TITLE
Crashes immediately in MacOS

### ISSUE THREAD

**Issue by fladd** [mujx/nheko#391]
### System:

- Nheko version: 0.5.1
- Installation method: dmg
- Operating System: MacOS 10.13.6

### Actual behavior

I open Nheko, I see the app for a second (with a spinning icon, apparently loading), Nheko closes, MacOS brings up a problem report.
### Steps to reproduce
Start Nheko

### Logs
terminating with uncaught exception of type nlohmann::detail::out_of_range: [json.exception.out_of_range.403] key 'groups' not found

[2018-07-28 01:27:49.522] [crypto] [critical] failed to upload one time keys: Unrecognised access token. 401

**Comment by mujx** [comment]
@fladd Are you using synapse?

**Comment by fladd** [comment]
Well, matrix.org does, but as I said I don't even get to login as the app crashes immediately when opening.

**Comment by mujx** [comment]
The logs indicate that there was a previous login with an invalid token. In any case, could you try the latest version (0.5.2) which should fix this issue?

**Comment by mujx** [comment]
Try clearing the cache `~/Library/Caches/nheko`  and the user configs `~/Library/Preferences/*nheko*`

**Comment by mujx** [comment]
@fladd Are there any update on this? Anything changed after clearing the cache data?

**Comment by fladd** [comment]
I could only clear the cache, since the second folder you mention does not exist on my machine. The behaviour is still the same. I only see the spinning large wheel.

**Comment by mujx** [comment]
@fladd Any luck with the latest version?

**Comment by fladd** [comment]
yes!
